// src/components/pdf/report-document.tsx
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { Report, Finding } from '@/lib/db/schema'
import type { Severity } from '@/lib/utils'

const SEVERITY_HEX: Record<Severity, string> = {
  critical: '#dc2626',
  high:     '#f97316',
  medium:   '#eab308',
  low:      '#3b82f6',
  info:     '#6b7280',
}

const styles = StyleSheet.create({
  page:          { fontFamily: 'Helvetica', fontSize: 10, padding: 40, color: '#1a1a1a' },
  coverPage:     { display: 'flex', flexDirection: 'column', justifyContent: 'center', height: '100%' },
  coverTitle:    { fontSize: 28, fontFamily: 'Helvetica-Bold', marginBottom: 8 },
  coverSub:      { fontSize: 14, color: '#555', marginBottom: 4 },
  coverMeta:     { fontSize: 10, color: '#777', marginTop: 24 },
  sectionTitle:  { fontSize: 14, fontFamily: 'Helvetica-Bold', marginBottom: 12, marginTop: 20,
                   borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 4 },
  table:         { display: 'flex', flexDirection: 'column', marginBottom: 16 },
  tableRow:      { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', padding: '4 0' },
  tableHeader:   { fontFamily: 'Helvetica-Bold', color: '#374151' },
  col1:          { width: '50%' },
  col2:          { width: '25%' },
  col3:          { width: '25%' },
  findingBox:    { marginBottom: 20, padding: 12, backgroundColor: '#f9fafb',
                   borderLeftWidth: 4, borderLeftColor: '#6b7280' },
  findingTitle:  { fontSize: 12, fontFamily: 'Helvetica-Bold', marginBottom: 6 },
  severityBadge: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#ffffff',
                   paddingHorizontal: 6, paddingVertical: 2, borderRadius: 3,
                   alignSelf: 'flex-start', marginBottom: 8 },
  label:         { fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  value:         { marginBottom: 8, lineHeight: 1.4 },
  evidence:      { fontFamily: 'Courier', fontSize: 8, backgroundColor: '#f3f4f6',
                   padding: 8, marginTop: 4 },
  footer:        { position: 'absolute', bottom: 24, left: 40, right: 40, fontSize: 8,
                   color: '#9ca3af', flexDirection: 'row', justifyContent: 'space-between' },
})

const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 }

function countBySeverity(findings: Finding[]) {
  const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 }
  for (const f of findings) {
    const s = (f.severity ?? 'info') as Severity
    counts[s]++
  }
  return counts
}

export function ReportDocument({ report, findings }: { report: Report; findings: Finding[] }) {
  const sorted = [...findings].sort((a, b) =>
    (severityOrder[a.severity ?? 'info'] ?? 4) - (severityOrder[b.severity ?? 'info'] ?? 4)
  )
  const counts = countBySeverity(findings)

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.coverPage}>
          <Text style={styles.coverTitle}>Penetration Test Report</Text>
          <Text style={styles.coverSub}>{report.clientName}</Text>
          {report.scope && <Text style={{ ...styles.coverMeta, marginTop: 8 }}>{report.scope}</Text>}
          <Text style={styles.coverMeta}>
            {report.startDate} – {report.endDate ?? 'ongoing'}
          </Text>
          {report.testerName && (
            <Text style={styles.coverMeta}>Prepared by: {report.testerName}</Text>
          )}
          <Text style={{ ...styles.coverMeta, marginTop: 32, color: '#374151' }}>
            Generated by PenPad · penpad.io
          </Text>
        </View>
      </Page>

      {/* Executive Summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={{ marginBottom: 16, lineHeight: 1.6 }}>
          This report presents the findings from a penetration test conducted against{' '}
          {report.clientName}
          {report.scope ? ` with scope: ${report.scope}` : ''}.
          The assessment was conducted between {report.startDate} and {report.endDate ?? 'present'}.
        </Text>

        <Text style={{ fontFamily: 'Helvetica-Bold', marginBottom: 8 }}>Findings Summary</Text>
        <View style={styles.table}>
          <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
            <Text style={styles.col1}>Severity</Text>
            <Text style={styles.col2}>Count</Text>
          </View>
          {(['critical', 'high', 'medium', 'low', 'info'] as Severity[]).map(s => (
            <View key={s} style={styles.tableRow}>
              <Text style={{ ...styles.col1, color: SEVERITY_HEX[s], fontFamily: 'Helvetica-Bold' }}>
                {s.toUpperCase()}
              </Text>
              <Text style={styles.col2}>{counts[s]}</Text>
            </View>
          ))}
          <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
            <Text style={styles.col1}>TOTAL</Text>
            <Text style={styles.col2}>{findings.length}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>PenPad</Text>
          <Text>{report.clientName} — Penetration Test Report</Text>
        </View>
      </Page>

      {/* Findings */}
      {sorted.map((finding, i) => {
        const severity = (finding.severity ?? 'info') as Severity
        return (
          <Page key={finding.id} size="A4" style={styles.page}>
            <Text style={styles.sectionTitle}>
              Finding {i + 1} of {sorted.length}
            </Text>
            <View style={{ ...styles.findingBox, borderLeftColor: SEVERITY_HEX[severity] }}>
              <Text style={styles.findingTitle}>{finding.title}</Text>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <Text style={{ ...styles.severityBadge, backgroundColor: SEVERITY_HEX[severity] }}>
                  {severity.toUpperCase()}
                </Text>
                <Text style={{ fontSize: 9, color: '#6b7280' }}>
                  CVSS Score: {Number(finding.cvssScore).toFixed(1)}
                </Text>
              </View>

              {finding.description && (
                <>
                  <Text style={styles.label}>Description</Text>
                  <Text style={styles.value}>{finding.description}</Text>
                </>
              )}
              {finding.impact && (
                <>
                  <Text style={styles.label}>Impact</Text>
                  <Text style={styles.value}>{finding.impact}</Text>
                </>
              )}
              {finding.recommendation && (
                <>
                  <Text style={styles.label}>Recommendation</Text>
                  <Text style={styles.value}>{finding.recommendation}</Text>
                </>
              )}
              {finding.evidence && (
                <>
                  <Text style={styles.label}>Evidence</Text>
                  <Text style={styles.evidence}>{finding.evidence}</Text>
                </>
              )}
            </View>

            <View style={styles.footer}>
              <Text>PenPad</Text>
              <Text>{report.clientName} — Finding {i + 1}/{sorted.length}</Text>
            </View>
          </Page>
        )
      })}
    </Document>
  )
}
